/* Stable place facts only. Preference tags and ordering are editorial, not conditions. */
'use strict';
globalThis.COAST_DATA = [
  {id:'pismo',name:'Pismo beachfront',fact:'The beaches lie immediately north and south of Pismo Beach Pier.',source:'https://experiencepismobeach.com/beach-and-outdoors/beaches/',vibes:['surf','coastal-walk','relax'],times:['morning','sunrise'],detail:'A beach-and-pier setting for an unhurried look at the ocean.',note:'Keep clear of pier structures and check posted notices before approaching the water.'},
  {id:'avila',name:'Avila beachfront',fact:'Avila Beach is a coastal town with a public beachfront.',source:'https://visitavilabeach.com/play-all-day-in-avila-beach/',vibes:['relax'],times:['midday','morning'],detail:'A straightforward beachfront stop when you want to pause rather than plan an expedition.',note:'Bring a layer and sun protection; this suggestion says nothing about today’s weather or crowds.'},
  {id:'dinosaur',name:'Dinosaur Caves Park',fact:'This oceanfront, bluff-top park is in the Shell Beach area of Pismo Beach.',source:'https://www.pismobeach.org/288/Dinosaur-Caves-Park',vibes:['coastal-walk','scenery'],times:['golden-hour','sunset'],detail:'An ocean-view park for a stroll or a long look from the bluff top.',note:'Stay on designated park paths and behind barriers. This is a viewpoint, not a route down the cliffs.'},
  {id:'morro',name:'Morro Rock Beach',fact:'Morro Rock Beach extends north from the base of Morro Rock.',source:'https://www.morrobayca.gov/383/Morro-Rock-Beach',vibes:['surf','scenery','coastal-walk'],times:['sunset','golden-hour'],detail:'A beach beside a distinctive coastal landmark, with room in the view for both rock and ocean.',note:'Stay off Morro Rock and the jetty. Check official beach notices and coastal advisories.'},
  {id:'spooners',name:'Spooner’s Cove',fact:'Spooner’s Cove is a beach in Montaña de Oro State Park, across from the campground.',source:'https://www.parks.ca.gov/?page_id=592',vibes:['scenery','relax'],times:['midday','morning'],detail:'A cove in a rugged coastal park for taking in the landscape.',note:'Check park access before leaving. Stay clear of cliff edges and rocks reached by waves.'}
];
